// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3Q8EZv6bUrgXalVj1-L8zRA7sXQ5a5E',
    appId: '1:506461167676:web:d508137700032d5e0de339',
    messagingSenderId: '506461167676',
    projectId: 'imm-app-6cc44',
    authDomain: 'imm-app-6cc44.firebaseapp.com',
    storageBucket: 'imm-app-6cc44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvSb8K8f7N8ieIm30pGwIKSanh70fTyo',
    appId: '1:506461167676:android:5e5ad1e3b2f4c5b70de339',
    messagingSenderId: '506461167676',
    projectId: 'imm-app-6cc44',
    storageBucket: 'imm-app-6cc44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAospHbNBlBi_6AO-ciVH4Nwv7lXlF9U4M',
    appId: '1:506461167676:ios:898908dd8b85c89c0de339',
    messagingSenderId: '506461167676',
    projectId: 'imm-app-6cc44',
    storageBucket: 'imm-app-6cc44.firebasestorage.app',
    iosBundleId: 'com.example.immApp',
  );
}
